[[paths_to_watch]]
path = "/app"
ignore = [
  "storage",
  "tmp",
  "log",
  "node_modules",
  "public/packs"
]

[[paths_to_watch]]
path = "/integration"

[processes.sidekiq]
command = "bin/rake"
args = [
  "jobs:work"
]
working_dir = "/app"

[processes.rails]
command = "bin/rails"
args = [
  "server",
  "--binding=0.0.0.0",
  "--port=4001"
]
working_dir = "/app"
